# Generated by Django 3.2.25 on 2024-06-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
